### PR TITLE
Overlay to display several time series

### PR DESCRIPTION
**Pull request by hdsingh**
Added feature to overlay  several time series of the selected variable on same map.
Screenshot from 2019-04-15 09-12-02

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
@hdsingh, this is a great step!   I love that the time series is not embedded in the same dashboard!

A few suggested fixes/improvements:
- the times are not displaying correctly
- hover is not working on the time series plots.    
- would be great to add time series locations on the map, perhaps as circles that have the same color as the time series plots?
- perhaps have a "clear" button to wipe the time series plots so the user can start again?

**Comment by hdsingh** [comment]
These suggestions are great!  
`Clear` button and `Circles` depicting location on map would certainly be very useful. These would make the dashboard more interactive and user friendly. 

I will implement these as soon as possible.

**Comment by rsignell-usgs** [comment]
Looks great!    I think I'm going to hold off on this until the time labels are working right, okay?

**Comment by hdsingh** [comment]
Screenshot from 2019-04-18 12-17-34

Hover is now working for multiple line curves and time labels are also in correct format.

**Comment by rsignell-usgs** [comment]
@hdsingh , awesome job.    @martindurant, check this out!

**Comment by hdsingh** [comment]
Thank you sir!!

**Comment by martindurant** [comment]
Am I right in thinking that air moves east to west in this scenario? That is not the way it usually goes around here (I live on the north shore of the coloured zone) :)

This is very nice. I could think of one more improvement: markers in the map area to show which timeseries line is from where. I assume the curve colours are just cycling in colour using the standard bokeh progression. 

I may ask some of my pyviz colleagues if there is a way to accelerate the redisplay following a click, which may become an issue with more complex layouts.

**Comment by hdsingh** [comment]
`Map markers` or `Circles` depicting location would definitely be a good feature to have. I would implement this as soon as possible.

Thanks!!

**Pull request merged**
